### ISSUE TITLE
Execute fn parameter expects a resolved function

### ISSUE THREAD

**Issue by hoetmaaiers** [icapps/tree-house#1]
I was struggling with the execute function over here: https://github.com/knor-el-snor/tree-house/blob/master/src/lib/base/BaseController.js#L18. This expects a Promise instead of an executable function. Is this by design?

**Comment by hoetmaaiers** [comment]
Nevermind, just passing an array, string or object is also fine...

**Comment by hoetmaaiers** [comment]
My mistake, `async/await` confused me... The execute function expects a Promise instance, is this correct?

**Comment by horstenwillem** [comment]
Mayor version release fixes this issue 🤓
